title: Sarthak Verma
logo: title: Sarthak Verma
logo: "/WhatsApp Image 2024-04-24 at 11.46.41 AM.jpg"
theme: jekyll-theme-minimal
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
