title: Sarthak Verma
logo: "https://github.com/sarthakmverma/headshot/blob/main/WhatsApp%20Image%202024-04-24%20at%2011.46.41%20AM.png"
theme: jekyll-theme-minimal
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
