title: Sarthak Verma
logo: WhatsApp Image 2024-04-24 at 11.46.41 AM_circle.png
theme: jekyll-theme-minimal
description: Smiling because coding is the easy part—real data science is making sense of the mess behind the scenes
#show_downloads: true
theme: jekyll-theme-minimal
